[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# https://book.getfoundry.sh/reference/config/solidity-compiler?highlight=allow_path#allow_paths
allow_paths = ['../../node_modules']
remappings = [
  'forge-std=node_modules/forge-std/src',
  'ds-test=node_modules/ds-test/src',
]
